<a href="https://colab.research.google.com/github/Ali-Radi/lab1/blob/main/Pandas%2BPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
file_path = "/content/drive/MyDrive/pandas/pandas/Data/Purchase_Data.csv"
df_data = pd.read_csv(file_path)
df_data.head()

Mounted at /content/drive

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [3]:
df_data.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

In [4]:
result_1 = df_data.loc[:, 'invoice_number':'invoice_time']
result_1.head()

   invoice_number   invoice_time
0    2.020000e+11  7/15/15 10:45
1    2.020000e+11  7/15/15 12:16
2    2.020000e+11  7/15/15 12:16
3    2.020000e+11  7/15/15 12:16
4    2.020000e+11  7/15/15 12:16

Slice the first two rows using .loc and store the result in a variable called result_2.

In [5]:
#Write you code here
result_2 = df_data.loc[0:1, :]
result_2.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [6]:
result_3 = df_data.iloc[0:4,0:5]
result_3.head()

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [7]:
#Write your code here
result_4 = df_data.loc[[0,4,6],['invoice_time','price']]
result_4.head()

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [8]:
num_rows = df_data.shape[0]
num_rows

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [9]:
print(df_data.iloc[num_rows-1,:])
#or
df_data.tail(1)

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [10]:
avg_price = df_data['price'].mean()
max_price = df_data['price'].max()
print('average price : ',avg_price)
print('max price : ',max_price)

average price :  3.1920522110741363
max price :  6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [11]:
avg_price= df_data['price'].sum() / num_rows
avg_num_items = df_data['num_item'].sum() / num_rows
print('average price : ', avg_price)
print('average num_items : ', avg_num_items)

average price :  3.1920522110741363
average num_items :  1.2983091787439613

Create a column called "total", which is the product of the price and num_item columns.

In [12]:
total = df_data['price'] * df_data['num_item']
df_data['total'] = total
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0

What is the avgerage price of the three most expensive purchases?

In [44]:
df_titanic = df_data.sort_values(by = 'price',ascending = False)
df_titanic.head(3)['price'].mean()

np.float64(6.003333333333333)

How many different products are there?

In [13]:
#Write your code here
df_data['product_id'].nunique()

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [14]:
#Write your code here
df_data['total'].describe()

count    5382.000000
mean        3.931808
std         5.820520
min         0.000000
25%         2.000000
50%         3.000000
75%         5.000000
max       348.000000
Name: total, dtype: float64

Use the drop() method to delete the column total from the dataframe df_data.

In [15]:
df_data = df_data.drop('total',axis = 1)
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Let's dig a little deeper into the data set and answer some basic question.

In [16]:
#Write your code here

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [17]:
#Write your code here
df_data['invoice_time'] = pd.to_datetime(df_data['invoice_time'])
df_data.dtypes

/tmp/ipython-input-4082526165.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_data['invoice_time'] = pd.to_datetime(df_data['invoice_time'])

invoice_number           float64
invoice_time      datetime64[ns]
store_id                  object
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
dtype: object

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [18]:
Dow = df_data['invoice_time'].dt.day_name()
Month = df_data['invoice_time'].dt.month
df_data['DOW'] = Dow
df_data['Month'] = Month
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,DOW,Month
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,Wednesday,7
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,7
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,7
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,Wednesday,7
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,Wednesday,7

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [19]:
#Write your code here
num_purchases_wed = df_data['DOW'].value_counts()['Wednesday']
print(num_purchases_wed)

959

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [20]:
file_path = "/content/drive/MyDrive/pandas/pandas/Data/Titanic.csv"
df_titanic = pd.read_csv(file_path)
df_titanic.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [21]:
df_titanic = df_titanic.rename(columns = {'Name':'Passenger_Name','Ticket':'Ticket_Num'})
df_titanic.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Change the index of the df_titanic to the column PasengerID.

In [22]:
df_titanic = df_titanic.set_index('PassengerId')
df_titanic.head()

,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Select the name of passenger 896

In [23]:
df_titanic.Passenger_Name[896]

'Hirvonen, Mrs. Alexander (Helga E Lindqvist)'

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [24]:
#
df_titanic = df_titanic.reset_index()
df_titanic.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [25]:
df_titanic['Age'].isnull().count()

np.int64(418)

Compute the avg age of passengers ignoring the missing data.

In [29]:
mean = df_titanic['Age'].mean()
mean

np.float64(30.272590361445783)

Using the fillna() method replace the missing values in the Age column with the mean.

In [30]:
df_titanic['Age'].fillna(mean)

0      34.50000
1      47.00000
2      62.00000
3      27.00000
4      22.00000
         ...
413    30.27259
414    39.00000
415    38.50000
416    30.27259
417    30.27259
Name: Age, Length: 418, dtype: float64

:What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [43]:
df_titanic = df_titanic.sort_values(by = 'Age',ascending = False)
df_titanic = df_titanic.reset_index(drop=True)
df_titanic.Age [0:5].mean()

np.float64(67.0)